add the function to output dockerfile
r-kurose/OpenRTP-aist pull request #1
Opened 2019-11-21 02:25 UTC by tonboAkinori

## Identify the Bug
- 無し

## Description of the Change

- RTC Builder に実行環境を作成する Dockerfile を出力する機能を追加
- 出力されたDockerfile の使い方
  - Docker のコンテキストに RTC Builder で作成したプロジェクトを含める
    - プロジェクト名とコンポーネント名が異なる場合は、Dockerfike の変更が必要
  - docker build 時に２つの引数を指定できる、引数を指定しない場合はデフォルト値が使用される。
    - 実行コマンド例
      - docker build --build-arg arch=arm32v7 --build-arg username=hoge -f 出力されたDockerfile .

| 引数 | デフォルト値 | 用途 |
|:-----------|:------------|:------------|
| arch           | amd64 | アーキテクチャの指定     |
| username  | noroot | 一般ユーザで起動する時の名前の指定   |

## Verification 
- [X] Did you succeed the build?  
- [ ] No warnings for the build?  
- [ ] Have you passed the unit tests?

2019-11-21 02:52 UTC, r-kurose commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +    && ln -s /usr/bin/python3 /usr/bin/python
PYTHON=/usr/bin/python3 ../configure に変更することで ln -s は不要

2019-11-21 03:05 UTC, r-kurose requested changes

2019-11-21 03:05 UTC, r-kurose commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +    && ln -s /usr/bin/python3 /usr/bin/python
九行目を対応すると、これも不要

2019-11-21 03:05 UTC, r-kurose commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +COPY ${rtcParam.name} /RTC
CMakefile があるフォルダで良い

2019-11-21 03:05 UTC, r-kurose commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +${sharp}${sharp}${sharp}${sharp}${sharp}${sharp}${sharp}${sharp}${sharp}${sharp}
`# ---------------------------` とかに変更しておく。文字列置換なしとする。

2019-11-21 03:05 UTC, r-kurose commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +COPY OpenRTM-aist /OpenRTM-aist
ADD or wget に変更する
https://github.com/OpenRTM/OpenRTM-aist/archive/master.zip

2019-11-21 03:05 UTC, r-kurose commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +ARG arch=amd64
arch 変数は、docker-buildx で悪さをする可能性があるからやめる

2019-11-22 02:34 UTC, tonboAkinori commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +COPY OpenRTM-aist /OpenRTM-aist
ADD で圧縮ファイルを扱う場合の挙動は リモートかローカルで挙動が変わる。
リモートの場合は取得（解凍はされなかった）、ローカルの場合は解凍。
レイヤが増えるため、今回は wget を使う方針にする。

2019-11-22 02:35 UTC, tonboAkinori commented on jp.go.aist.rtm.rtcbuilder/src/jp/go/aist/rtm/rtcbuilder/template/dockerfile/Dockerfile.vsl
> +    && ln -s /usr/bin/python3 /usr/bin/python
この処理がないとビルドが通らないため、この処理は残します。

2019-11-25 06:31 UTC, merged